name: linting

on: push

jobs:
  # first job named linting 
  linting:
    runs-on: ${{ matrix.os }}

  strategy:
    matrix:
      os : [ubuntu-latest, windows-latest, macOS-latest]
      version : ['3.9', '3.8']

    steps:
      - name : code checkout
        uses: actions/checkout@v2

      - name : setup python
        uses : actions/setup-python@v2
        with:
          python-vesrion: ${{ matrix.version }}
      - name : install flaske8
        run: |
          python -m pip install --upgrade pip
          pip install flask8
      - name : run flake8
        run : |
          flaske8 app.py
