name: linting

on: push

jobs:
  # first job named linting 
  linting:
    runs-on: ubuntu-latest

    steps:
      - name : code checkout
        uses: actions/checkout@v2

      - name : setup python
        uses : actions/setup-python@v2
        with:
          python-vesrion: '3.9'
      - name : install flaske8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name : run flake8
        run : |
          flaske8 app.py
          